# Site settings
title: 'Chase Courington' # Your Title
tagline: 'enjoy the ride' # A brief tagline for your site
sidebar_image: /images/cover.jpg

# Build settings
markdown: redcarpet
highlighter: pygments
