# Site settings
title: 'SIMPLBREW' # Your Title
tagline: 'Chase Courington - UI Developer' # A brief tagline for your site
sidebar_image: /images/cover.jpg

# Build settings
markdown: kramdown
kramdown:
  input: GFM
highlighter: pygments
